# Generated by Django 5.2.1 on 2026-06-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsehistory',
            name='last_watched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='browsehistory',
            name='newly_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='browsehistory',
            name='recently_opened',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
